DROP TABLE NotificationRecord;
DROP TABLE DeploymentStatusNotificationConfiguration_Organization_UserAccount;
DROP TABLE DeploymentStatusNotificationConfiguration_DeploymentTarget;
DROP TABLE DeploymentStatusNotificationConfiguration;
